// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderAPI.Models.Context;

#nullable disable

namespace ProductAPI_1.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderAPI.Models.Entities.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerGSM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmonut")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderAPI.Models.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(8196),
                            Description = "Deleniti umut architecto quam alias quae sit aspernatur voluptatum otobüs.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 615.20m
                        },
                        new
                        {
                            ID = 2,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(8479),
                            Description = "Dolores dağılımı non eaque gülüyorum cezbelendi autem exercitationem sayfası masaya.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 787.87m
                        },
                        new
                        {
                            ID = 3,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(8586),
                            Description = "Değerli commodi ut eos bilgisayarı aut consequuntur gazete voluptas cezbelendi.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 156.13m
                        },
                        new
                        {
                            ID = 4,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(8652),
                            Description = "Eos orta deleniti çakıl yazın çıktılar ratione inventore laudantium doğru.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 367.94m
                        },
                        new
                        {
                            ID = 5,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(8717),
                            Description = "Voluptatum dergi voluptate tempora odio umut illo rem doğru ki.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 755.30m
                        },
                        new
                        {
                            ID = 6,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(8778),
                            Description = "Çorba bilgiyasayarı aliquam qui masaya sıradanlıktan karşıdakine quae qui architecto.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 546.47m
                        },
                        new
                        {
                            ID = 7,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(8883),
                            Description = "Veritatis ea salladı ea ad ea gitti ekşili yazın lambadaki.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 663.50m
                        },
                        new
                        {
                            ID = 8,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(8953),
                            Description = "Layıkıyla adipisci koştum sevindi anlamsız quis quia sıfat quasi un.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 732.46m
                        },
                        new
                        {
                            ID = 9,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9018),
                            Description = "Kapının doloremque qui un sıradanlıktan rem açılmadan layıkıyla camisi olduğu.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 323.47m
                        },
                        new
                        {
                            ID = 10,
                            Category = "Electronics",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9077),
                            Description = "Voluptate oldular değirmeni sarmal et ut cesurca sinema labore ve.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 700.06m
                        },
                        new
                        {
                            ID = 11,
                            Category = "Books",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9161),
                            Description = "Değirmeni ki doloremque öyle lakin ratione eos in dolor voluptate.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 469.07m
                        },
                        new
                        {
                            ID = 12,
                            Category = "Books",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9223),
                            Description = "Quis sevindi umut aliquam in bilgisayarı esse consectetur domates orta.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 596.66m
                        },
                        new
                        {
                            ID = 13,
                            Category = "Books",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9279),
                            Description = "Quae enim layıkıyla değirmeni quia çakıl telefonu sit quasi bilgisayarı.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 571.86m
                        },
                        new
                        {
                            ID = 14,
                            Category = "Books",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9337),
                            Description = "Rem sokaklarda domates totam magni accusantium praesentium kapının ratione bilgisayarı.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 86.45m
                        },
                        new
                        {
                            ID = 15,
                            Category = "Books",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9394),
                            Description = "Ut öyle qui magni salladı çakıl balıkhaneye voluptatem lambadaki biber.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 383.93m
                        },
                        new
                        {
                            ID = 16,
                            Category = "Books",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9475),
                            Description = "Için enim layıkıyla çarpan odio açılmadan balıkhaneye aperiam quia dolayı.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 541.47m
                        },
                        new
                        {
                            ID = 17,
                            Category = "Books",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9531),
                            Description = "Sunt nesciunt sed yapacakmış kapının masanın quia domates vitae uzattı.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 368.67m
                        },
                        new
                        {
                            ID = 18,
                            Category = "Books",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9590),
                            Description = "Doloremque şafak veniam duyulmamış explicabo sarmal çünkü voluptatem eum ışık.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 885.62m
                        },
                        new
                        {
                            ID = 19,
                            Category = "Books",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9653),
                            Description = "Okuma laudantium un numquam quia aut ullam bilgiyasayarı mutlu makinesi.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 200.78m
                        },
                        new
                        {
                            ID = 20,
                            Category = "Books",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9750),
                            Description = "Tempora aliquid düşünüyor layıkıyla odit odit bilgiyasayarı doloremque sevindi bundan.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 884.13m
                        },
                        new
                        {
                            ID = 21,
                            Category = "Clothing",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9816),
                            Description = "Perferendis adanaya sequi öyle iure deleniti türemiş sit telefonu eos.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 958.66m
                        },
                        new
                        {
                            ID = 22,
                            Category = "Clothing",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9873),
                            Description = "Quis filmini voluptas quae uzattı dolore masaya bahar doloremque consectetur.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 949.57m
                        },
                        new
                        {
                            ID = 23,
                            Category = "Clothing",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 329, DateTimeKind.Local).AddTicks(9929),
                            Description = "Voluptatum aliquid velit enim dolayı yaptı oldular duyulmamış gülüyorum bilgiyasayarı.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 118.57m
                        },
                        new
                        {
                            ID = 24,
                            Category = "Clothing",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(8),
                            Description = "Vel labore anlamsız sokaklarda consectetur nesciunt bundan aliquam ut ex.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 22.13m
                        },
                        new
                        {
                            ID = 25,
                            Category = "Clothing",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(65),
                            Description = "Makinesi alias ut voluptate salladı sevindi mıknatıslı mutlu quia odit.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 837.33m
                        },
                        new
                        {
                            ID = 26,
                            Category = "Clothing",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(120),
                            Description = "Perferendis iusto dolores nemo nisi odio açılmadan ki yaptı beatae.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 246.52m
                        },
                        new
                        {
                            ID = 27,
                            Category = "Clothing",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(177),
                            Description = "Dicta exercitationem çünkü yapacakmış voluptatum bilgiyasayarı quia adresini autem sıfat.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 602.52m
                        },
                        new
                        {
                            ID = 28,
                            Category = "Clothing",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(254),
                            Description = "Umut vel gidecekmiş aut consectetur bilgisayarı telefonu için et göze.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 390.95m
                        },
                        new
                        {
                            ID = 29,
                            Category = "Clothing",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(315),
                            Description = "Aut dolor lakin bahar aut velit odio aut incidunt perferendis.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 286.08m
                        },
                        new
                        {
                            ID = 30,
                            Category = "Clothing",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(369),
                            Description = "Şafak eve bilgisayarı sokaklarda türemiş kutusu et magnam aperiam koyun.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 27.59m
                        },
                        new
                        {
                            ID = 31,
                            Category = "Beauty",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(431),
                            Description = "Voluptatem modi eum velit quasi dolorem sarmal bundan magnam vitae.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 706.93m
                        },
                        new
                        {
                            ID = 32,
                            Category = "Beauty",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(485),
                            Description = "Layıkıyla accusantium ipsum blanditiis sokaklarda sayfası suscipit iure rem reprehenderit.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 763.90m
                        },
                        new
                        {
                            ID = 33,
                            Category = "Beauty",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(570),
                            Description = "Sed ex orta lakin eaque mi adipisci teldeki sequi uzattı.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 641.69m
                        },
                        new
                        {
                            ID = 34,
                            Category = "Beauty",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(626),
                            Description = "Et umut mıknatıslı voluptatem quaerat karşıdakine çünkü odit odio sayfası.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 373.73m
                        },
                        new
                        {
                            ID = 35,
                            Category = "Beauty",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(681),
                            Description = "Nostrum voluptas kalemi enim ut eve dicta açılmadan architecto quis.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 987.39m
                        },
                        new
                        {
                            ID = 36,
                            Category = "Beauty",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(736),
                            Description = "Balıkhaneye consequatur domates fugit masanın mi sokaklarda sıfat camisi eum.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 32.81m
                        },
                        new
                        {
                            ID = 37,
                            Category = "Beauty",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(817),
                            Description = "Gördüm accusantium rem ut şafak sequi gördüm için dergi anlamsız.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 709.54m
                        },
                        new
                        {
                            ID = 38,
                            Category = "Beauty",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(871),
                            Description = "Doğru bilgiyasayarı gazete in dağılımı göze lakin sayfası filmini fugit.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 199.26m
                        },
                        new
                        {
                            ID = 39,
                            Category = "Beauty",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(923),
                            Description = "Quia layıkıyla eius quia numquam makinesi kutusu uzattı minima çakıl.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 669.42m
                        },
                        new
                        {
                            ID = 40,
                            Category = "Beauty",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(978),
                            Description = "Laudantium beğendim çıktılar beatae veniam uzattı telefonu velit perferendis consequatur.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 14.92m
                        },
                        new
                        {
                            ID = 41,
                            Category = "Toys",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(1056),
                            Description = "Doğru totam lakin dolayı esse yazın dağılımı eum şafak odio.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 390.57m
                        },
                        new
                        {
                            ID = 42,
                            Category = "Toys",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(1111),
                            Description = "Beatae beatae corporis balıkhaneye ea quaerat consequatur ki kapının quis.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 392.25m
                        },
                        new
                        {
                            ID = 43,
                            Category = "Toys",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(1167),
                            Description = "Ut voluptatem non göze aut velit deleniti quasi quam dolayı.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 388.17m
                        },
                        new
                        {
                            ID = 44,
                            Category = "Toys",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(1220),
                            Description = "Masanın aliquam domates veritatis ekşili çünkü molestiae cesurca biber eius.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 684.79m
                        },
                        new
                        {
                            ID = 45,
                            Category = "Toys",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(1298),
                            Description = "Domates batarya sokaklarda voluptate quia filmini inventore commodi makinesi beatae.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 662.86m
                        },
                        new
                        {
                            ID = 46,
                            Category = "Toys",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(1354),
                            Description = "Bundan koyun velit modi nisi ipsa mi doloremque ullam iure.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 652.61m
                        },
                        new
                        {
                            ID = 47,
                            Category = "Toys",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(1407),
                            Description = "Perferendis de molestiae öyle gül reprehenderit adipisci quis voluptas aspernatur.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 177.06m
                        },
                        new
                        {
                            ID = 48,
                            Category = "Toys",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(1461),
                            Description = "Consequatur bilgiyasayarı aut dolayı labore ratione şafak sevindi mi explicabo.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 538.08m
                        },
                        new
                        {
                            ID = 49,
                            Category = "Toys",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(1535),
                            Description = "Vel praesentium consectetur eve tempora aperiam magni velit quia sarmal.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 522.34m
                        },
                        new
                        {
                            ID = 50,
                            Category = "Toys",
                            CreatedDate = new DateTime(2023, 5, 1, 19, 57, 8, 330, DateTimeKind.Local).AddTicks(1591),
                            Description = "Ducimus patlıcan amet sed dolores sokaklarda oldular laudantium sequi voluptatem.",
                            Status = 0,
                            Unit = 150,
                            UnitPrice = 180.61m
                        });
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<int>("OrdersID")
                        .HasColumnType("int");

                    b.Property<int>("ProductsID")
                        .HasColumnType("int");

                    b.HasKey("OrdersID", "ProductsID");

                    b.HasIndex("ProductsID");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("OrderAPI.Models.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderAPI.Models.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
